development:
  dialect: postgres
  datasource: dbname=jb_tenant sslmode=disable
  dir: migrations/tenants

tenantdb:
  dialect: postgres
  datasource: host=${TENANT_DB_HOST} port=${TENANT_DB_PORT} user=${TENANT_DB_USER} password=${TENANT_DB_PASSWORD} dbname=${TENANT_DB_NAME} sslmode=disable
  dir: migrations/tenants

systemdb:
  dialect: postgres
  datasource: host=${SYSTEM_DB_HOST} port=${SYSTEM_DB_PORT} user=${SYSTEM_DB_USER} password=${SYSTEM_DB_PASSWORD} dbname=${SYSTEM_DBNAME} sslmode=disable
  dir: migrations/system
