development:
  dialect: postgres
  datasource: dbname=jb_tenant sslmode=disable
  dir: migrations/tenants

tenantdb:
  dialect: postgres
  datasource: host=${DATABASE_TENANT_HOST} port=${DATABASE_TENANT_PORT} user=${DATABASE_TENANT_USERNAME} password=${DATABASE_TENANT_PASSWORD} dbname=${DATABASE_TENANT_DBNAME} sslmode=disable
  dir: migrations/tenants

systemdb:
  dialect: postgres
  datasource: host=${DATABASE_SYSTEM_HOST} port=${DATABASE_SYSTEM_PORT} user=${DATABASE_SYSTEM_USERNAME} password=${DATABASE_SYSTEM_PASSWORD} dbname=${DATABASE_SYSTEM_DBNAME} sslmode=disable
  dir: migrations/system
